language: php
cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.2
    - 7.3
    - 7.4

env:
    - SYMFONY_VERSION=3.4.*
    - SYMFONY_VERSION=4.0.*
    - SYMFONY_VERSION=4.1.*
    - SYMFONY_VERSION=4.2.*
    - SYMFONY_VERSION=4.3.*
    - SYMFONY_VERSION=4.4.*
    - SYMFONY_VERSION=5.0.*

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar global require hirak/prestissimo
    - php composer.phar require symfony/form:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/security-bundle:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/yaml:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/config:${SYMFONY_VERSION} --no-update
    - php composer.phar require symfony/dependency-injection:${SYMFONY_VERSION} --no-update
    - COMPOSER_MEMORY_LIMIT=-1 php composer.phar update --no-interaction

script:
    - php composer.phar run-test-suite
